version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - POSTGRES_DB=flaskdb
      - POSTGRES_USER=flaskuser
      - POSTGRES_PASSWORD=flaskpass
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=flaskdb
      - POSTGRES_USER=flaskuser
      - POSTGRES_PASSWORD=flaskpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
